services:
  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: ${NGINX_CONTAINER}
    restart: unless-stopped
    ports:
      - ${SERVICE_PORT}:80
    volumes:
      - ${VOLUME_PATH}
      - ${CONF_PATH}
    networks:
      - local-network

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_CONTAINER}
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      TZ: ${TZ}
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - local-network

  app:
    user: ${USER_ID}:${GROUP_ID}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - WORK_DIR=${WORK_DIR}
    image: ${APP_IMAGE}
    container_name: ${APP_CONTAINER}
    restart: unless-stopped
    working_dir: ${WORK_DIR}
    volumes:
      - ${VOLUME_PATH}
    networks:
      - local-network
    ports:
      - '${PORT_VITE}:5174'

  phpmyadmin:
    build: ./phpmyadmin
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_ARBITRARY=1
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD_ROOT}
      - MAX_EXECUTION_TIME=${PMA_MAX_EXECUTION_TIME}
      - MEMORY_LIMIT=${PMA_MEMORY_LIMIT}
      - UPLOAD_LIMIT=${PMA_UPLOAD_LIMIT}
    networks:
      - local-network

volumes:
  mysql:

networks:
  local-network:
    external: true